name: words_native
description: Easywords android application
display_name: Easywords

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: 2.0.1
  cached_network_image: ^3.1.0
  dartz: ^0.10.0
  device_info: ^2.0.2
  dio: ^4.0.0
  flash: ^2.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.17.0
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^0.14.2
  hooks_riverpod: ^0.14.0+4
  intl: ^0.17.0
  json_annotation: ^4.0.1
  material_design_icons_flutter: ^5.0.5955-rc.1
  oauth2: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.4
  sembast: ^3.1.0+2
  shimmer: ^2.0.0
  webview_flutter: ^2.0.13
  flip_card: ^0.6.0
  adaptive_theme: ^2.3.0
  flutter_native_splash: ^1.2.3
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^0.14.2
  lint: ^1.6.0
  auto_route_generator: 2.0.1
  json_serializable:

flutter:
  assets:
    - assets/images/easywords-full.png
    - assets/images/logo.png
  uses-material-design: true
flutter_intl:
  enabled: true
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/easywords-full.png
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
